### ISSUE TITLE
XSS Vulnerability on the Guestbook example for php-redis

### ISSUE THREAD

**Issue by gabidavila** [GoogleCloudPlatform/kubernetes-engine-samples#170]
Someone reached out to me about this possible path of exploitation through XSS on this part of the code:

https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/guestbook/php-redis/guestbook.php#L39

`$_GET` here is not recommend, since you could override any value just by guessing a key, or setting arbitrary keys.

The recommendation I make it is maybe to do an API endpoint?

**Comment by NimJay** [comment]
Hi @gabidavila.

First, thanks for bringing up this concern!

I realize that it's been a long time since you reported this issue — so I'm sorry to make you jog your memory back so far.
Here's a refresher:
* This sample app just keeps track of a list of names (a guestbook).
* It comprises of: 
  * an AngularJS webpage; 
  * a PHP `guestbook.php` HTTP endpoint; and 
  * a Redis key-value database.
* The guestbook names are stored in the Redis key-value database, under the `messages` key like so: `"Katy Perry, John Lenon, Paul McCartney"`.
* The a PHP `guestbook.php` HTTP endpoint allows for retrieval and modification of values at _any_ key — not just the `messages` key.
* The AngularJS webpage talks to the `guestbook.php` endpoint to save and retrieve names (the guestbook). 

If possible, could you please elaborate on what you mean by:
> The recommendation I make it is maybe to do an API endpoint?
Do you mean we should replace `guestbook.php` with an HTTP endpoint that only allows for retrieval and modification of values at the `messages` key?

Let me know if you have any questions (and feel free to ping me on Google Chat).
Thank you!

**Comment by NimJay** [comment]
I'm closing this issue as it has been addressed by https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/202.
@gabidavila Feel free to ignore the above question(s). Thank you! :)
