### ISSUE TITLE
Host whereami images in EU

### ISSUE THREAD

**Issue by boredabdel** [GoogleCloudPlatform/kubernetes-engine-samples#669]
Hi,

The only artifact i found for the whereami app is in the US (us-docker.pkg.dev)

Do you push the image to a AR in Europe as well or not ?

**Comment by NimJay** [comment]
Hi @boredabdel! :)
Unfortunately, all images from this repository that are pushed to AR (Artifact Registry) are only pushed to `us-docker.pkg.dev`. See [all images here](https://pantheon.corp.google.com/artifacts/docker/google-samples/us/containers?mods=pan_ng2). (Let me know if you need access.)

**Comment by boredabdel** [comment]
Who should we get in touch with to setup an EU repository ?

**Comment by NimJay** [comment]
Thanks for the quick repsonse, @boredabdel.

I don't think there's a single owner of the `google-samples` repo.
So I've gone ahead and created a new Artifact Registry (AR) for Europe — with the same name and description as the existing US AR repository.
However, for changes related to _this_ repo, you'd need approval from [my team](https://g3doc.corp.google.com/company/teams/cloud-devrel/dee/teams/platform_ops/index.md?cl=head) — so I can help with merging any of your pull-request.

### Questions

**1.** Which images did you want to make available in the Europe cluster?
**2.** If you know which images you want in the Europe AR repository, please feel free to create a pull-request. You would just need to add some lines into the existing cloudbuild.yaml files (see [example `cloudbuild.yaml` file here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/cloudbuild.yaml#L26)).
**3.** If you'd like to edit the new Europe AR repo, feel free to do so. I have made you an AR admin on `google-samples`.

### Cost of new Europe AR repository

In case anyone is curious about the cost of the newly created AR repository in Europe: it'll likely just $2 extra per month.
According to the [AR pricing page](https://cloud.google.com/artifact-registry/pricing):
* storage is $0.10 per GB, per month. The storage used up by the existing US AR repository is 15.5 GB. So that's about $2 a month — just for storage.
* the cost of network egress in US is the cost in Europe. I don't imagine an additional registry changing the number of image downloads, so the new Europe AR repository won't add to the existing network egress cost.

**Comment by NimJay** [comment]
So sorry, I just realized this is about `whereami`! 🤦 

... so we'll need @theemadnes's approval.
And I've gone ahead and created the pull-request: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/670

**Comment by NimJay** [comment]
@boredabdel
The `whereami` image is now available at europe-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20.
That said, we should favour using `us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20` for cloud.google.com documentation.

**Comment by boredabdel** [comment]
Thank you 🙏
